name: zint_flutter
description: A Flutter package for generating barcodes using Zint library
version: 1.0.0
homepage: https://github.com/julienangx/zint_flutter
repository: https://github.com/julienangx/zint_flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
